# Generated by Django 2.2.4 on 2019-09-27 15:44

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('words_exchanged', otree.db.models.IntegerField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_simple_survey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'my_simple_survey_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('settings', otree.db.models.StringField(max_length=10000, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_simple_survey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'my_simple_survey_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('chat_earnings', otree.db.models.CurrencyField(default=0, null=True)),
                ('chat_status', otree.db.models.StringField(max_length=10000, null=True)),
                ('disconnected_timestamp', models.DateTimeField(blank=True, null=True)),
                ('reach_payoff', otree.db.models.FloatField(default=0, null=True)),
                ('early_finish', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('payoff_set', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('wp_timer_start', models.DateTimeField(blank=True, null=True)),
                ('sec_spent', otree.db.models.IntegerField(null=True)),
                ('sec_earned', otree.db.models.FloatField(null=True)),
                ('in_wp', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('unmatched', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('wp_passed', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('is_it_still_knowledge', otree.db.models.StringField(choices=[('True', 'Yes, Bob knows that Jill drives an American car'), ('False', 'No, Bob does not know that Jill drives an American car')], max_length=10000, null=True, verbose_name='Does Bob know that Jill drives an American car?')),
                ('still_confidence', otree.db.models.IntegerField(choices=[(1, 'Not confident at all'), (2, ''), (3, ''), (4, 'Somewhat confident'), (5, ''), (6, ''), (7, 'Very confident')], null=True)),
                ('reason', otree.db.models.LongStringField(blank=True, null=True, verbose_name='Please explain in 2-3 lines why you did or did not change\n                                   your initial answer to this question')),
                ('experience', otree.db.models.StringField(choices=[('True', 'Yes, I have read a story very similar to this one before.'), ('False', 'No, I have never read a story very similar to this one.')], max_length=10000, null=True, verbose_name='Have you ever read a story like the one in \n                                      this experiment in any other context before?')),
                ('age', otree.db.models.IntegerField(null=True, verbose_name='How old are you?')),
                ('gender', otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='What is your gender?')),
                ('race', otree.db.models.StringField(choices=[('White', 'White'), ('Latino', 'Latino'), ('Black', 'African American'), ('Native American', 'Native American'), ('Asian or Pacific Islander', 'Asian'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='What is your race?')),
                ('education', otree.db.models.StringField(choices=[('None', 'No schooling completed'), ('Grade School', 'Nursery school to 8th grade'), ('Some HS', 'Some high school, no diploma'), ('HS', 'High school graduate, diploma or the equivalent (for example: GED)'), ('Some College', 'Some college credit, no degree'), ('Trade School', 'Trade/technical/vocational training'), ('Associate', 'Associate degree'), ('Bachelor', 'Bachelor’s degree'), ('Associate', 'Master’s degree'), ('Professional', 'Professional degree'), ('Doctorate', 'Doctorate degree'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='What is the highest level of education you have achieved?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_simple_survey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_simple_survey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_simple_survey_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_simple_survey.Subsession')),
            ],
            options={
                'db_table': 'my_simple_survey_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_simple_survey.Subsession'),
        ),
    ]
