# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 18:50
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_simple_survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chat_earnings',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
