# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 19:44
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_simple_survey', '0002_player_chat_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='still_confidence',
            field=otree.db.models.StringField(choices=[(1, 'Not confident at all'), (2, ''), (3, 'Somewhat confident'), (4, ''), (5, 'Very confident')], max_length=10000, null=True),
        ),
    ]
