# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 22:27
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_simple_survey', '0004_auto_20180211_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='still_confidence',
            field=otree.db.models.IntegerField(choices=[(1, 'Not confident at all'), (2, ''), (3, ''), (4, 'Somewhat confident'), (5, ''), (6, ''), (7, 'Very confident')], null=True),
        ),
    ]
