# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 22:36
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_simple_survey', '0005_auto_20180211_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chat_earnings',
            field=otree.db.models.CurrencyField(default=0, null=True),
        ),
    ]
