# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 22:43
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_simple_survey', '0006_auto_20180211_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='words_exchanged',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
