# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gettier_init_group', to='otree.Session')),
            ],
            options={
                'db_table': 'gettier_init_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('choices_order', otree.db.models.StringField(max_length=10000, null=True)),
                ('is_it_knowledge', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Does Bob know that Jill drives an American car? ')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gettier_init.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gettier_init_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gettier_init_player', to='otree.Session')),
            ],
            options={
                'db_table': 'gettier_init_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='SettingsMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', otree.db.models.StringField(default='Does Bob know that Jill drives an American car? ', max_length=10000, null=True, verbose_name='Question for vignette')),
                ('vignette', otree.db.models.StringField(default='Bob has a friend, Jill, who has driven a Buick for many years. Bob therefore thinks that Jill drives an American car. He is not aware, however, that her Buick has recently been stolen, and he is also not aware that Jill has replaced it with a Pontiac, which is a different kind of American car.', max_length=10000, null=True, verbose_name='Vignette text')),
                ('yes_choice', otree.db.models.StringField(default='Yes, he knows it', max_length=10000, null=True, verbose_name="Text for 'Yes' answer")),
                ('no_choice', otree.db.models.StringField(default='No, he does not know it', max_length=10000, null=True, verbose_name="Text for 'No' answer")),
                ('min_chat_sec', otree.db.models.IntegerField(default=60, null=True, verbose_name='Minimum time on chat page, in seconds')),
                ('max_chat_sec', otree.db.models.IntegerField(default=300, null=True, verbose_name='Maximum time on chat page, in seconds')),
                ('pay_per_min', otree.db.models.FloatField(default=0.1, null=True, verbose_name='How much a person earned for minute of waiting')),
                ('wait_before_leave', otree.db.models.IntegerField(default=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('settings', otree.db.models.StringField(max_length=10000, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gettier_init_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'gettier_init_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettier_init.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gettier_init.Subsession'),
        ),
    ]
