# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 13:45
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('gettier_init', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmod',
            name='chat_instructions',
            field=otree.db.models.StringField(default='You are now in a chat room with a person who gave the opposite answer to you. Each player should try to convince the other player of his/her answer. After debating for (at most) 4 minutes, you will both be given a chance to change your original answer. Player 1 should begin by explaining his/her answer to Player 2. For your reference, here is the original case:', max_length=10000, null=True, verbose_name='Instructions for chat'),
        ),
    ]
