# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 18:43
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('gettier_init', '0002_settingsmod_chat_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmod',
            name='chat_earnings',
            field=otree.db.models.FloatField(default=0.05, null=True, verbose_name='How much a person earned for a word exchanged in chat'),
        ),
    ]
