# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 21:32
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('gettier_init', '0007_auto_20180211_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='confidence',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
