# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 21:35
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('gettier_init', '0010_auto_20180211_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='confidence',
            field=otree.db.models.IntegerField(choices=[[1, 'Not confident at all'], [2, 'a'], [3, 'b'], [4, 'Somewhat confident'], [5, 'c'], [6, 'd'], [7, 'Very confident']], null=True),
        ),
    ]
